pipeline {
   agent any
   stages{
      stage('checkout'){
         steps{
            checkout scm
         }
      }
      stage('Build image') {
            when {
                changeset "tor-browser/*"
            }
            steps {
                echo 'Building tor-browser image, please wait ...'

                script {
                    withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
                       def customImage = docker.build("xavibj/tor-browser:${env.BUILD_ID}","-f tor-browser/Dockerfile .")
                       def latest = docker.build("xavibj/tor-browser:latest","-f tor-browser/Dockerfile .")
                       customImage.push()
                       latest.push()
                    }
                }
            }
       }
   }
}
