pipeline {
   agent any
   stages{
      stage('checkout'){
         steps{
            checkout scm
         }
      }
      stage('Build image') {
            steps {
                echo 'Starting to build docker image ... !'

                script {
                    withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
                       def customImage = docker.build("xavibj/atom:${env.BUILD_ID}","-f atom/Dockerfile .")
                       def latest = docker.build("xavibj/atom:latest","-f atom/Dockerfile .")
                       customImage.push()
                       latest.push()
                    }
                }
            }
       }
   }
}
